version: 2
updates:
  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: semiannually
    open-pull-requests-limit: 3
    groups:
      angular:
        patterns:
          - "@angular/*"
          - "@angular-devkit/*"
        update-types:
          - minor
          - patch
      other-npm-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "@angular/*"
          - "@angular-devkit/*"
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major

  - package-ecosystem: maven
    directory: /backend
    schedule:
      interval: semiannually
    open-pull-requests-limit: 3
    groups:
      maven-dependencies:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major

  - package-ecosystem: docker
    directory: /frontend
    schedule:
      interval: semiannually
    open-pull-requests-limit: 1
    groups:
      docker-images:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: semiannually
    open-pull-requests-limit: 1
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major