import { describe, it, expect } from 'vitest';
import * as fc from 'fast-check';

/**
 * Property-Based Testing for Data Validation
 * 
 * These tests use fast-check to generate random inputs and verify
 * that our validation and calculation functions maintain mathematical
 * properties and invariants.
 */

// Helper validation functions (these would normally be imported from utilities)
const isValidEmail = (email: string): boolean => {
  const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
  return emailRegex.test(email);
};

const normalizePrice = (price: number): number => {
  if (isNaN(price) || !isFinite(price)) return 0;
  // `price * 100` can overflow to Infinity for very large finite doubles
  // (e.g. 1e308), so the result needs the same guard as the input — otherwise
  // normalizePrice is not idempotent at the top of the range.
  const rounded = Math.round(price * 100) / 100;
  if (!isFinite(rounded)) return 0;
  return Math.max(0, rounded);
};

const normalizeSKU = (sku: string): string => {
  return sku.trim().toUpperCase().replace(/\s+/g, '-');
};

const calculateAvailable = (onHand: number, reserved: number): number => {
  const oh = Math.max(0, Math.floor(onHand));
  const res = Math.max(0, Math.floor(reserved));
  return Math.max(0, oh - res);
};

const calculateOrderSubtotal = (items: { quantity: number; unitPrice: number }[]): number => {
  return items.reduce((sum, item) => {
    const qty = Math.max(0, item.quantity);
    const price = normalizePrice(item.unitPrice);
    return sum + (qty * price);
  }, 0);
};

const calculateTax = (subtotal: number, taxRate: number): number => {
  const normalizedSubtotal = normalizePrice(subtotal);
  const normalizedRate = Math.max(0, Math.min(1, taxRate));
  return normalizePrice(normalizedSubtotal * normalizedRate);
};

const calculateTotal = (subtotal: number, tax: number): number => {
  return normalizePrice(subtotal + tax);
};

describe('Property-Based Testing: Data Validation', () => {
  
  describe('Email Validation Properties', () => {
    it('accepts all valid email addresses generated by fast-check', () => {
      fc.assert(
        fc.property(fc.emailAddress(), (email) => {
          expect(isValidEmail(email)).toBe(true);
        }),
        { numRuns: 100 }
      );
    });

    it('rejects strings without @ symbol', () => {
      fc.assert(
        fc.property(
          fc.string().filter(s => !s.includes('@')),
          (str) => {
            if (str.length === 0) return; // Empty strings are handled separately
            expect(isValidEmail(str)).toBe(false);
          }
        ),
        { numRuns: 100 }
      );
    });

    it('rejects strings with @ but no domain', () => {
      fc.assert(
        fc.property(
          fc.string().map(s => s + '@'),
          (str) => {
            expect(isValidEmail(str)).toBe(false);
          }
        ),
        { numRuns: 50 }
      );
    });
  });

  describe('Price Normalization Properties', () => {
    it('always returns non-negative prices', () => {
      fc.assert(
        fc.property(fc.double(), (price) => {
          const normalized = normalizePrice(price);
          expect(normalized).toBeGreaterThanOrEqual(0);
        }),
        { numRuns: 200 }
      );
    });

    it('rounds to 2 decimal places', () => {
      fc.assert(
        fc.property(
          fc.double({ min: 0, max: 10000, noNaN: true }),
          (price) => {
            const normalized = normalizePrice(price);
            const decimalPlaces = (normalized.toString().split('.')[1] || '').length;
            expect(decimalPlaces).toBeLessThanOrEqual(2);
          }
        ),
        { numRuns: 200 }
      );
    });

    it('is idempotent (normalizing twice gives same result)', () => {
      fc.assert(
        fc.property(fc.double(), (price) => {
          const normalized1 = normalizePrice(price);
          const normalized2 = normalizePrice(normalized1);
          expect(normalized1).toBe(normalized2);
        }),
        { numRuns: 200 }
      );
    });

    it('handles NaN and Infinity as zero', () => {
      expect(normalizePrice(NaN)).toBe(0);
      expect(normalizePrice(Infinity)).toBe(0);
      expect(normalizePrice(-Infinity)).toBe(0);
    });
  });

  describe('SKU Normalization Properties', () => {
    it('is idempotent (normalizing twice gives same result)', () => {
      fc.assert(
        fc.property(fc.string(), (sku) => {
          const normalized1 = normalizeSKU(sku);
          const normalized2 = normalizeSKU(normalized1);
          expect(normalized1).toBe(normalized2);
        }),
        { numRuns: 200 }
      );
    });

    it('always returns uppercase strings', () => {
      fc.assert(
        fc.property(fc.string(), (sku) => {
          const normalized = normalizeSKU(sku);
          expect(normalized).toBe(normalized.toUpperCase());
        }),
        { numRuns: 200 }
      );
    });

    it('replaces whitespace with hyphens', () => {
      fc.assert(
        fc.property(
          fc.string().filter(s => s.includes(' ')),
          (sku) => {
            const normalized = normalizeSKU(sku);
            expect(normalized).not.toContain(' ');
          }
        ),
        { numRuns: 100 }
      );
    });

    it('has no leading or trailing whitespace', () => {
      fc.assert(
        fc.property(fc.string(), (sku) => {
          const normalized = normalizeSKU(sku);
          expect(normalized).toBe(normalized.trim());
        }),
        { numRuns: 200 }
      );
    });
  });

  describe('Inventory Calculation Properties', () => {
    it('available quantity never exceeds on-hand quantity', () => {
      fc.assert(
        fc.property(
          fc.integer({ min: 0, max: 10000 }),
          fc.integer({ min: 0, max: 10000 }),
          (onHand, reserved) => {
            const available = calculateAvailable(onHand, reserved);
            expect(available).toBeLessThanOrEqual(onHand);
          }
        ),
        { numRuns: 300 }
      );
    });

    it('available quantity is always non-negative', () => {
      fc.assert(
        fc.property(
          fc.integer({ min: 0, max: 10000 }),
          fc.integer({ min: 0, max: 10000 }),
          (onHand, reserved) => {
            const available = calculateAvailable(onHand, reserved);
            expect(available).toBeGreaterThanOrEqual(0);
          }
        ),
        { numRuns: 300 }
      );
    });

    it('available equals on-hand when no reservations', () => {
      fc.assert(
        fc.property(
          fc.integer({ min: 0, max: 10000 }),
          (onHand) => {
            const available = calculateAvailable(onHand, 0);
            expect(available).toBe(onHand);
          }
        ),
        { numRuns: 200 }
      );
    });

    it('available is zero when reserved exceeds on-hand', () => {
      fc.assert(
        fc.property(
          fc.integer({ min: 0, max: 1000 }),
          fc.integer({ min: 1001, max: 10000 }),
          (onHand, reserved) => {
            const available = calculateAvailable(onHand, reserved);
            expect(available).toBe(0);
          }
        ),
        { numRuns: 200 }
      );
    });

    it('handles negative inputs gracefully', () => {
      fc.assert(
        fc.property(
          fc.integer({ min: -1000, max: 1000 }),
          fc.integer({ min: -1000, max: 1000 }),
          (onHand, reserved) => {
            const available = calculateAvailable(onHand, reserved);
            expect(available).toBeGreaterThanOrEqual(0);
          }
        ),
        { numRuns: 200 }
      );
    });

    it('handles fractional inputs by flooring', () => {
      expect(calculateAvailable(10.7, 3.2)).toBe(7); // floor(10.7) - floor(3.2) = 10 - 3 = 7
      expect(calculateAvailable(5.9, 5.1)).toBe(0); // floor(5.9) - floor(5.1) = 5 - 5 = 0
    });
  });

  describe('Order Calculation Properties', () => {
    it('order subtotal equals sum of item subtotals', () => {
      fc.assert(
        fc.property(
          fc.array(
            fc.record({
              quantity: fc.integer({ min: 1, max: 100 }),
              unitPrice: fc.double({ min: 0.01, max: 1000, noNaN: true })
            }),
            { minLength: 1, maxLength: 20 }
          ),
          (items) => {
            const orderSubtotal = calculateOrderSubtotal(items);

            const manualTotal = items.reduce((sum, item) => {
              return sum + (item.quantity * normalizePrice(item.unitPrice));
            }, 0);
            
            expect(orderSubtotal).toBeCloseTo(manualTotal, 2);
          }
        ),
        { numRuns: 100 }
      );
    });

    it('empty order has zero subtotal', () => {
      const subtotal = calculateOrderSubtotal([]);
      expect(subtotal).toBe(0);
    });

    it('order subtotal is always non-negative', () => {
      fc.assert(
        fc.property(
          fc.array(
            fc.record({
              quantity: fc.integer({ min: -100, max: 100 }),
              unitPrice: fc.double({ min: -1000, max: 1000, noNaN: true })
            }),
            { maxLength: 10 }
          ),
          (items) => {
            const subtotal = calculateOrderSubtotal(items);
            expect(subtotal).toBeGreaterThanOrEqual(0);
          }
        ),
        { numRuns: 100 }
      );
    });
  });

  describe('Tax Calculation Properties', () => {
    it('tax is always non-negative', () => {
      fc.assert(
        fc.property(
          fc.double({ min: 0, max: 100000, noNaN: true }),
          fc.double({ min: 0, max: 1, noNaN: true }),
          (subtotal, taxRate) => {
            const tax = calculateTax(subtotal, taxRate);
            expect(tax).toBeGreaterThanOrEqual(0);
          }
        ),
        { numRuns: 200 }
      );
    });

    it('tax never exceeds subtotal when rate is 100% or less', () => {
      fc.assert(
        fc.property(
          fc.double({ min: 0, max: 100000, noNaN: true }),
          fc.double({ min: 0, max: 1, noNaN: true }),
          (subtotal, taxRate) => {
            // calculateTax rounds to cents, so for a sub-cent subtotal the tax
            // can round up past the raw value (0.045 -> 0.05). The invariant
            // holds against the normalized subtotal, which is what the
            // calculation actually operates on.
            const tax = calculateTax(subtotal, taxRate);
            expect(tax).toBeLessThanOrEqual(normalizePrice(subtotal));
          }
        ),
        { numRuns: 200 }
      );
    });

    it('zero tax rate results in zero tax', () => {
      fc.assert(
        fc.property(
          fc.double({ min: 0, max: 100000, noNaN: true }),
          (subtotal) => {
            const tax = calculateTax(subtotal, 0);
            expect(tax).toBe(0);
          }
        ),
        { numRuns: 100 }
      );
    });

    it('handles tax rates outside [0, 1] by clamping', () => {
      expect(calculateTax(100, -0.5)).toBe(0); // Negative rate clamped to 0
      expect(calculateTax(100, 1.5)).toBe(100); // Rate > 1 clamped to 1
    });
  });

  describe('Total Calculation Properties', () => {
    it('total equals subtotal plus tax', () => {
      fc.assert(
        fc.property(
          fc.double({ min: 0, max: 100000, noNaN: true }),
          fc.double({ min: 0, max: 10000, noNaN: true }),
          (subtotal, tax) => {
            const total = calculateTotal(subtotal, tax);
            const expected = normalizePrice(subtotal + tax);
            expect(total).toBeCloseTo(expected, 2);
          }
        ),
        { numRuns: 200 }
      );
    });

    it('total is at least as large as subtotal', () => {
      fc.assert(
        fc.property(
          fc.double({ min: 0, max: 100000, noNaN: true }),
          fc.double({ min: 0, max: 10000, noNaN: true }),
          (subtotal, tax) => {
            const total = calculateTotal(subtotal, tax);
            expect(total).toBeGreaterThanOrEqual(normalizePrice(subtotal));
          }
        ),
        { numRuns: 200 }
      );
    });

    it('total is always non-negative', () => {
      fc.assert(
        fc.property(
          fc.double(),
          fc.double(),
          (subtotal, tax) => {
            const total = calculateTotal(subtotal, tax);
            expect(total).toBeGreaterThanOrEqual(0);
          }
        ),
        { numRuns: 200 }
      );
    });
  });

  describe('End-to-End Order Calculation Properties', () => {
    it('full order calculation maintains consistency', () => {
      fc.assert(
        fc.property(
          fc.array(
            fc.record({
              quantity: fc.integer({ min: 1, max: 50 }),
              unitPrice: fc.double({ min: 0.01, max: 500, noNaN: true })
            }),
            { minLength: 1, maxLength: 10 }
          ),
          fc.double({ min: 0, max: 0.2, noNaN: true }), // Tax rate 0-20%
          (items, taxRate) => {
            const subtotal = calculateOrderSubtotal(items);
            const tax = calculateTax(subtotal, taxRate);
            const total = calculateTotal(subtotal, tax);
            
            // Verify relationships. `total`, `subtotal` and `tax` are each
            // rounded to cents along different code paths, so the ordering
            // comparisons have to tolerate a floating-point ULP.
            const EPSILON = 1e-9;
            expect(total).toBeGreaterThanOrEqual(subtotal - EPSILON);
            expect(total).toBeGreaterThanOrEqual(tax - EPSILON);
            expect(subtotal + tax).toBeCloseTo(total, 2);
          }
        ),
        { numRuns: 100 }
      );
    });
  });
});
